name: DynamicSeasons
version: '${project.version}'
main: de.tomasgng.DynamicSeasons
api-version: 1.19
authors: [TomasGnG]
description: Make your worlds more beautiful with seasons.
softdepend:
  - PlaceholderAPI
commands:
  dynamicseasons:
    description: Main command for DynamicSeasons
    aliases:
      - dynseasons
      - dseasons
